### ISSUE TITLE
Encountering Issues When Reproducing Code

### ISSUE THREAD

**Issue by zhuyuzy** [LordLiang/DrawingSpinUp#18]
Thank you for providing such concise cod. 

I encountered difficulties while reproducing the code. 

I followed the step-by-step instructions in the readme, but only a small portion of the information from the original images was preserved in the generated GIF. 

Could you inspire me on how to reproduce the results from your paper?
![jumping_res_stage2_mask_pos_edge](https://github.com/user-attachments/assets/134420e1-146b-481f-87fe-90616c358eb7)

**Comment by dbstjswo505** [comment]
Yes, I am also facing similar problem...
The quality is not good, different from the author's presented ones.
![dab_res_stage2_mask_pos_edge](https://github.com/user-attachments/assets/5a85ef1a-037e-4928-ab98-00bb79be9b89)

**Comment by zhuyuzy** [comment]
I'm closing this issue because the issue is fixed with help of the author, thanks a lot.

The decline in quality is due to the requirement that .obj files must correspond one-to-one with .fbx files. 

If you run Step 2, the .obj files will be modified, making the provided .fbx files in the dataset incompatible. 

You will need to generate your own .fbx files. Alternatively, you can run Step 3 directly, which will yield the same results as those in the paper.

**Comment by dbstjswo505** [comment]
Thank you for your response i am also reproducing 1,2,3. By the way how much time it takes to perform 3 phase?

**Comment by zhuyuzy** [comment]
The other steps only took a few minutes, but running `python run_render.py --uid YOUR_EXAMPLE_ID --test` took a long time.
