### ISSUE TITLE
Xlib:  extension "XInputExtension" missing on display ":1".

### ISSUE THREAD

**Issue by Wenretium** [LordLiang/DrawingSpinUp#3]
Hello, thanks for the great work! 
I followed your instructions in the 'Try A Toy' section and ran the command:
`python run_render.py --uid ff7ab74a67a443e3bda61e69577f4e80`
However, I encountered the following error:
`Xlib:  extension "XInputExtension" missing on display ":1".`
The full error is as follows.
![image](https://github.com/user-attachments/assets/d46dc16f-6781-4717-ba16-7dcedfc13519)
I believe the issue is caused by a Blender rendering failure. I have installed the version of Blender provided by you, and I am remotely connecting to the server via SSH (without a graphical interface). The operating system is Ubuntu 16.04.

**Comment by LordLiang** [comment]
I am sorry I do not know how to deal with this error. But I think you can run the rendering scripts on a laptop (Mac or Win...) with a graphical interface and then transmit the rendered frames to your Ubuntu for training.

**Comment by mhjiang0408** [comment]
Same error. And I wish you would provide a docker image for easier deployment.

**Comment by LordLiang** [comment]
Hi, I find that `export DISPLAY=:1` may not always work for all systems. Maybe you can try `export DISPLAY=:0`.
![error](https://github.com/user-attachments/assets/4fb06b36-ae3b-4c4b-8096-38cc4f44125b)

**Comment by Wenretium** [comment]
I edit the rendering codes following https://github.com/LordLiang/DrawingSpinUp/issues/6#issue-2536056453, and the issue is solved. Thank all of you.
